# Generated by Django 2.1.4 on 2018-12-20 06:44

from django.db import migrations, models
import django.db.models.deletion
import foodmenow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('price_min', models.CharField(max_length=5)),
                ('price_max', models.CharField(max_length=5)),
                ('review_min', models.IntegerField()),
                ('review_max', models.IntegerField()),
                ('food_genre', models.CharField(choices=[(foodmenow.models.FOOD_GENRE_CHOICES('Malaysian'), 'Malaysian'), (foodmenow.models.FOOD_GENRE_CHOICES('Chinese'), 'Chinese'), (foodmenow.models.FOOD_GENRE_CHOICES('Indian'), 'Indian')], default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.CharField(max_length=255)),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='preferences',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodmenow.Users'),
        ),
    ]
