# Generated by Django 2.1.4 on 2018-12-23 15:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, default=5)),
                ('price_min', models.CharField(blank=True, max_length=5)),
                ('price_max', models.CharField(blank=True, max_length=5)),
                ('rating_min', models.CharField(blank=True, max_length=5)),
                ('rating_max', models.CharField(blank=True, max_length=5)),
                ('food_genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), size=None)),
            ],
            options={
                'verbose_name_plural': 'Preference',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password_hash', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.CharField(blank=True, max_length=256)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodmenow.Users'),
        ),
    ]
