# Generated by Django 2.1.4 on 2018-12-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='distance',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
