# Generated by Django 2.1.4 on 2018-12-20 06:45

from django.db import migrations, models
import foodmenow.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='food_genre',
            field=models.CharField(choices=[(foodmenow.models.FOOD_GENRE_CHOICES('Malaysian'), 'Malaysian'), (foodmenow.models.FOOD_GENRE_CHOICES('Chinese'), 'Chinese'), (foodmenow.models.FOOD_GENRE_CHOICES('Indian'), 'Indian')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_hash',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
