# Generated by Django 2.1.4 on 2018-12-27 06:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0002_auto_20181225_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='food_genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=256), size=None),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_max',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_min',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating_max',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating_min',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
