# Generated by Django 2.1.4 on 2018-12-27 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0003_auto_20181227_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='food_genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=256), null=True, size=None),
        ),
    ]
