# Generated by Django 2.1.4 on 2018-12-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0004_auto_20181227_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='price_max',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_min',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating_max',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating_min',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
