# Generated by Django 2.1.4 on 2018-12-27 07:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0006_auto_20181227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='food_genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=256), blank=True, null=True, size=None),
        ),
    ]
