# Generated by Django 2.1.4 on 2018-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenow', '0007_auto_20181227_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='distance',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_max',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_min',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating_max',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating_min',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
